name-template: 'halostatue/halostatue Actions v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # [#@] disable mentions, [`] disables code blocks
template: |
  ## Changes

  $CHANGES

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    label: 'chore'
  - title: 'Dependency Updates'
    labels:
      - 'dependencies'
      - 'github_actions'

version-resolver:
  major:
    labels:
      - 'actions/major'
  minor:
    labels:
      - 'actions/minor'
  patch:
    labels:
      - 'actions/patch'
  default: patch

include-labels:
  - 'actions/major'
  - 'actions/minor'
  - 'actions/patch'
