name: Fish Tests

on:
  workflow_call:

permissions: {}

jobs:
  check-fish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@fa20e922736577a305eaa1b09f9254de84c4d019 #v2.0.5
      - uses: fish-shop/indent-check@c40e7d55e0b4e64a02ff0f3c53ee9309956de031 #v2.2.51
      - uses: fish-shop/syntax-check@2182de0e2108df8958cb1c3f0f234bf670b3c2e0 #v2.2.50
      - uses: fish-shop/install-plugin@42ba5a60cd3e5edb9061d8ffddb7835c2aaa7c96 #v2.3.53
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@1b50224e7be74d009442bd85dfc6b02b98f329fc #v2.3.53
