name: Fish Tests

on:
  workflow_call:

permissions: {}

jobs:
  check-fish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@77357e8d1e20d0ebf75e1f11424113c2ac63e5f5 #v2.0.12
      - uses: fish-shop/indent-check@3c1c072ca0fd70c22f1c67884dbc40edda4a1cfe #v2.2.58
      - uses: fish-shop/syntax-check@6f9107b315ab8a926b946a169b6724bfdfb817b5 #v2.2.57
      - uses: fish-shop/install-plugin@cd2fe5aa2caaa1b7f4bdedc23ae4a6e6821fc142 #v2.3.60
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@34a576410dc59d4dc8d32ae0344b2ad0b3519dcd #v2.3.60
