name: Fish Tests

on:
  workflow_call:

permissions: {}

jobs:
  check-fish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@2f0191376af2ee2c7bc14513f24c7d8520cb47b1 #v2.0.11
      - uses: fish-shop/indent-check@c19eebf7885b9775d854461b2778888f0d6fe3f2 #v2.2.57
      - uses: fish-shop/syntax-check@32440c4fe514616ae09f526930afd77956e4bac4 #v2.2.56
      - uses: fish-shop/install-plugin@187a1c8bf8d685e983f87d2c34c8e60657cc01cd #v2.3.59
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@2b011e8523f36765596701f2fc77cc54760bc435 #v2.3.59
