name: Fish Tests

on:
  workflow_call:

permissions: {}

jobs:
  check-fish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@a70eb5492192c2748530e1d5d7e44314ed69daf1 #v2.0.10
      - uses: fish-shop/indent-check@52827cd0adf0e82c9bf2657e3dfdb65f97abfa60 #v2.2.56
      - uses: fish-shop/syntax-check@ceb14da30e4397e0cfcae40fe6815eb325be7d63 #v2.2.55
      - uses: fish-shop/install-plugin@b40425d0939eb4b21d420efda9b2b626c9b8232e #v2.3.58
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@b8734270d05d020940d610fcda5371cb517e3fbc #v2.3.58
