name: Fish Tests

on:
  workflow_call:

permissions: {}

jobs:
  check-fish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@338fc69f5b910baf93d13a2a7d964d762ff35015 #v2.0.9
      - uses: fish-shop/indent-check@eb4cd511a693c6efe788e563d42915247692eda7 #v2.2.55
      - uses: fish-shop/syntax-check@acba3b3503d1f5d33945ac5ada946ca928cd1497 #v2.2.54
      - uses: fish-shop/install-plugin@75887998c88ea9f0d040b8519dbd44b408815cfa #v2.3.57
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@82d492c450aaac6f7ce86ed0c9794d065e1570c3 #v2.3.57
