name: Fish Tests

on:
  workflow_call:

permissions: {}

jobs:
  check-fish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@b74f33f8d92d162542be7995a9a6bae7afc8e919 #v2.0.6
      - uses: fish-shop/indent-check@5506c0a0f923199697ba27ea9e7f631a92eee2fd #v2.2.52
      - uses: fish-shop/syntax-check@d9389c3cde18bb45412fb1a9cfdd744888a142fb #v2.2.51
      - uses: fish-shop/install-plugin@66a42e7652a6213fcf68c7960e4562dd372bd867 #v2.3.54
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@b06693dcdfab5e656e5284c7d7791200340991f0 #v2.3.54
