name: Fish Tests

on:
  workflow_call:

permissions: {}

jobs:
  check-fish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@99fb15ad1a1d32abcfd0806727176149a9372ef5 #v2.0.13
      - uses: fish-shop/indent-check@f376dae366a52109cab577361872b76f6ebbfaa0 #v2.2.59
      - uses: fish-shop/syntax-check@982fe1a18186d615a9aad5b4b600bbef62f8eb54 #v2.2.58
      - uses: fish-shop/install-plugin@474f455fef7e715e98e65f2c561b72bcc0f3cec3 #v2.3.61
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@16825d76cab6d0c5888ab2b15868c9c029782287 #v2.3.61
