name: Fish Tests

on:
  workflow_call:

permissions: {}

jobs:
  check-fish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@2b19219f82cce7c9f053cb99e23f7e3df47f56e9 #v2.0.1
      - uses: fish-shop/indent-check@e8cfa080b8a298eeebd8e0408d5a747a55d42ab1 #v2.2.46
      - uses: fish-shop/syntax-check@65c1057b266055a3e99e7a30be73f0aa48a40987 #v2.2.45
      - uses: fish-shop/install-plugin@581520d006079b0f1ad28496a258025189fcb355 #v2.3.48
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@908e7b211d08adc702042166db106230ef8131d2 #v2.3.48
